### ISSUE TITLE
你好，请问代码会公开吗？

### ISSUE THREAD

**Issue by zhangqinghua1008** [RuoyuGuo/MaskGA_Net#1]
如果公开的话，会在什么时间公开呢？

**Comment by RuoyuGuo** [comment]
你好， 我们正在将方法进一步更新， 并且投递到新的journal中。 我们也希望能提供一个更方便使用的代码， 且能够在不同的dataset上使用， 所以公开的时间会再晚一些， 谢谢你的耐心。

**Comment by RuoyuGuo** [comment]
代码已公布
