### ISSUE TITLE
Questions about the "10-fold cross validation".

### ISSUE THREAD

**Issue by WilliamLee30** [RuoyuGuo/MaskGA_Net#4]
Hello! Thank you for your great work.
When I try to replicate the experiment on MoNuSeg dataset, a problem occurs in analyzing the code of 10-fold cross validation e.g I can't find where you implement the 10-fold cross validation. Because I find that you split the dataset into training, validation, and test sets in "_datasplit" function of "my_dataset.py", but this is done only once instead of 10 times. Also in "train.py", the model is trained only once instead of 10 times with different dataset split at the require of 10-fold cross validation. Could you please tell me how you implement 10-fold cross validation and release the code?
Best regards.

**Comment by RuoyuGuo** [comment]
Hi, if you look at the 207-208 line in` train.py,` there is a parameter named` k_fold.` You can use a different value of` k_fold` to run `train.py` 10 times to get 10-fold cross validation results.

**Comment by WilliamLee30** [comment]
> Hi, if you look at the 207-208 line in` train.py,` there is a parameter named` k_fold.` You can use a different value of` k_fold` to run `train.py` 10 times to get 10-fold cross validation results.

I get it, thanks a lot!
