### ISSUE TITLE
f

### ISSUE THREAD

**Issue by yanyi999** [RuoyuGuo/MaskGA_Net#5]
作者你好，我用的数据集是TNBC，在用模型SAC时f_seg那一列的图像显示为全黑图片，您能告诉一下是什么问题吗？谢谢啦
![Uploa
![Figure_1](https://github.com/user-attachments/assets/b4194581-242b-41b6-bca9-737614fb95a7)
ding image.png…]()

**Comment by RuoyuGuo** [comment]
你好，如果我没记错的话， 我当时TNBC存储的segmentation结果， 应该是只用了0和1的值去分别代表background和foreground。但是存储为图片时，pixel的值的范围是0~255，所以存储后你直接打开应该全是黑的，但你要是用python读成numpy array，然后用matplotlib显示出来的话应该就能看到background和foreground的了。 或者你可以选择在存储的时候乘个255，就会有内容显示出来了。

**Comment by yanyi999** [comment]
非常感谢您的回复，我明天仔细试一下，谢谢您！

---- Replied Message ----
| From | Ruoyu ***@***.***> |
| Date | 09/10/2024 21:23 |
| To | RuoyuGuo/MaskGA_Net ***@***.***> |
| Cc | yanyi999 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) |

你好，如果我没记错的话， 我当时TNBC存储的segmentation结果， 应该是只用了0和1的值去分别代表background和foreground。但是存储为图片时，pixel的值的范围是0~255，所以存储后你直接打开应该全是黑的，但你要是用python读成numpy array，然后用matplotlib显示出来的话应该就能看到background和foreground的了。 或者你可以选择在存储的时候乘个255，就会有内容显示出来了。

**Comment by yanyi999** [comment]
您好，冒昧打扰您了，我看了一下您的源代码，在输出图片的时候已经把张量转化成了numpy array ，不知道为什么用SAC模型和Seg_Att模型的时候输出来是全黑的，但是用模型为seg的时候就可以出来分割结果图，不晓得哪里出了问题。再次寻求您的帮助，非常感谢您！  


---- Replied Message ----
| From | Ruoyu ***@***.***> |
| Date | 9/10/2024 21:24 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) |

你好，如果我没记错的话， 我当时TNBC存储的segmentation结果， 应该是只用了0和1的值去分别代表background和foreground。但是存储为图片时，pixel的值的范围是0~255，所以存储后你直接打开应该全是黑的，但你要是用python读成numpy array，然后用matplotlib显示出来的话应该就能看到background和foreground的了。 或者你可以选择在存储的时候乘个255，就会有内容显示出来了。

**Comment by RuoyuGuo** [comment]
> Author
> ###

你好， 你在training的时候，training过程自带的evaluation给出的数值，比如IOU和DICE，会有提高吗

**Comment by yanyi999** [comment]
您好，这两个值都没有提高，甚至有点减小了


---- Replied Message ----
| From | Ruoyu ***@***.***> |
| Date | 9/11/2024 10:31 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) |

Author

你好， 你在training的时候，training过程自带的evaluation给出的数值，比如IOU和DICE，会有提高吗

**Comment by RuoyuGuo** [comment]
> 您好，这两个值都没有提高，甚至有点减小了
> […](#)
> ---- Replied Message ---- | From | Ruoyu ***@***.***> | | Date | 9/11/2024 10:31 | | To | ***@***.***> | | Cc | ***@***.***>, ***@***.***> | | Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) | Author 你好， 你在training的时候，training过程自带的evaluation给出的数值，比如IOU和DICE，会有提高吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

数值大概多少呀？

**Comment by yanyi999** [comment]
大概是这样的，真是麻烦您了！



---- Replied Message ----
| From | Ruoyu ***@***.***> |
| Date | 9/11/2024 10:41 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) |

您好，这两个值都没有提高，甚至有点减小了
…
---- Replied Message ---- | From | Ruoyu @.> | | Date | 9/11/2024 10:31 | | To | @.> | | Cc | @.>, @.> | | Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) | Author 你好， 你在training的时候，training过程自带的evaluation给出的数值，比如IOU和DICE，会有提高吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

数值大概多少呀？

**Comment by RuoyuGuo** [comment]
你好，你是发了图片吗，我好像看不到。

**Comment by yanyi999** [comment]
是的呢，不好意思哈，您这边方便加您个微信不？


---- Replied Message ----
| From | Ruoyu ***@***.***> |
| Date | 9/11/2024 10:54 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) |

你好，你是发了图片吗，我好像看不到。

**Comment by yanyi999** [comment]
以附件的形式可以看到吗？
---- Replied Message ----
| From | Ruoyu ***@***.***> |
| Date | 9/11/2024 10:54 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) |

你好，你是发了图片吗，我好像看不到。

**Comment by RuoyuGuo** [comment]
> 是的呢，不好意思哈，您这边方便加您个微信不？
> […](#)
> ---- Replied Message ---- | From | Ruoyu ***@***.***> | | Date | 9/11/2024 10:54 | | To | ***@***.***> | | Cc | ***@***.***>, ***@***.***> | | Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) | 你好，你是发了图片吗，我好像看不到。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

行，但不一定能及时给你解决，这个代码有点早了，有些我也要回忆回忆

**Comment by yanyi999** [comment]
好的呢，您方便的话可以加我一下15760363507，您能回复我已经很感谢您了！


---- Replied Message ----
| From | Ruoyu ***@***.***> |
| Date | 9/11/2024 11:27 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) |

是的呢，不好意思哈，您这边方便加您个微信不？
…
---- Replied Message ---- | From | Ruoyu @.> | | Date | 9/11/2024 10:54 | | To | @.> | | Cc | @.>, @.> | | Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) | 你好，你是发了图片吗，我好像看不到。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

行，但不一定能及时给你解决，这个代码有点早了，有些我也要回忆回忆

**Comment by RuoyuGuo** [comment]
> 好的呢，您方便的话可以加我一下15760363507，您能回复我已经很感谢您了！
> […](#)
> ---- Replied Message ---- | From | Ruoyu ***@***.***> | | Date | 9/11/2024 11:27 | | To | ***@***.***> | | Cc | ***@***.***>, ***@***.***> | | Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) | 是的呢，不好意思哈，您这边方便加您个微信不？ … ---- Replied Message ---- | From | Ruoyu @.> | | Date | 9/11/2024 10:54 | | To | @.> | | Cc | @.>, @.> | | Subject | Re: [RuoyuGuo/MaskGA_Net] f (Issue #5) | 你好，你是发了图片吗，我好像看不到。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***> 行，但不一定能及时给你解决，这个代码有点早了，有些我也要回忆回忆 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

好，已经加了。
